In [11]:
# Import the data
pbp_data = nfl.import_pbp_data([2024], include_participation=False)
roster_data = nfl.import_weekly_rosters([2024])

# Filter for regular season passing touchdowns
pass_td_data = pbp_data[
    (pbp_data["season_type"] == "REG") &
    (pbp_data["two_point_attempt"] == False) &
    (pbp_data["play_type"] == "pass") &
    (pbp_data["pass_touchdown"] == 1)
]

# Merge with roster data
pass_td_data = pass_td_data.merge(
    roster_data[["player_id", "player_name"]], 
    left_on="passer_player_id", 
    right_on="player_id",
    how='inner'
)

# Drop duplicate plays to count unique touchdowns
pass_td_data_unique = pass_td_data.drop_duplicates(subset=['game_id', 'play_id'])

# Group and count unique touchdowns
pass_td_agg = pass_td_data_unique.groupby(
    ["player_name"], 
    as_index=False
)["pass_touchdown"].count()

# Sort and format
pass_td_agg.sort_values(
    by=['pass_touchdown'], 
    inplace=True, 
    ascending=False
)

pass_td_agg.rename(
    columns={
        'player_name': 'Player Name',
        "pass_touchdown": "Total Passing TD's"
    }, 
    inplace=True
)

# Get top 10
pass_td_agg = pass_td_agg.head(10)

pass_td_agg

2024 done.
Downcasting floats.

        Player Name  Total Passing TD's
28       Joe Burrow                  27
36    Lamar Jackson                  25
5    Baker Mayfield                  24
26       Jared Goff                  20
43      Sam Darnold                  19
31       Josh Allen                  18
34     Kirk Cousins                  17
0     Aaron Rodgers                  17
30      Jordan Love                  16
41  Patrick Mahomes                  15